import type { Attempt, Leader, Profile, Run, Suite, System } from '../src/types';

export const profiles: Profile[] = [
  { id: 'mock-reference', label: 'Reference agent', adapter: 'pi', model: 'test-router', enabled: true, pricing: { source: "Test rates", effective_date: "2026-09-23", input_per_million: 1 }, preflight: { status: 'ready', version: 'test-1.0', authentication: 'ready', warnings: [], capabilities: { usage: true, reported_cost: true, route: true, tool_events: true } } },
  { id: 'mock-baseline', label: 'Baseline agent', adapter: 'codex', model: 'test-fixed', enabled: true, preflight: { status: 'ready', version: 'test-1.0', authentication: 'ready', warnings: [], capabilities: { usage: true, reported_cost: false, route: false, tool_events: true } } },
  { id: 'missing', label: 'Unavailable CLI', adapter: 'claude', model: 'test-alias', enabled: true, preflight: { status: 'missing', version: '', authentication: 'not_checked', warnings: ['CLI executable not found. Install the CLI and run preflight.'], capabilities: { usage: false, reported_cost: false, route: false, tool_events: false } } },
];
export const system: System = { version: '0.1.0', local_only: true, mock_enabled: true, defaults: { timeout_seconds: 900, attempts_per_case: 1, mode: 'sequential' }, storage: { keep_workspaces: false, retention_days: 30 }, warnings: [] };
export const suite: Suite = { id: 'python-smoke', name: 'Python smoke', version: '1.0.0', hash: 'same-suite-fingerprint', description: 'A focused check of local execution, hidden tests, and deterministic scoring.', cases: [{ id: 'RB-PY-001', title: 'Normalize configuration values', category: 'Bug repair', difficulty: 'Easy', tags: ['python'], prompt: 'Fix the configuration parser without changing its public API.', timeout_seconds: 900 }, { id: 'RB-PY-002', title: 'Implement bounded retries', category: 'Feature implementation', difficulty: 'Medium', tags: ['python'], prompt: 'Implement bounded retries for transient failures.', timeout_seconds: 900 }] };
const attemptBase: Attempt = { id: 'attempt-ref-1', run_id: 'run-one', case_id: 'RB-PY-001', profile_id: 'mock-reference', attempt_index: 1, execution_order: 0, status: 'passed', score: 1, full_pass: true, agent_duration_ms: 12000, preparation_duration_ms: 100, grading_duration_ms: 500, input_tokens: 1800, output_tokens: 400, cached_input_tokens: 0, reasoning_tokens: null, cost_usd: .01, cost_provenance: 'reported', tool_calls: 3, turns: 2, retries: 0, configured_model: 'test-router', primary_observed_model: 'test-fast', exit_code: 0, error_code: null, error_message: null, files_changed: 1, lines_added: 3, lines_removed: 1, created_at: '2026-09-23T10:00:00Z', started_at: '2026-09-23T10:00:01Z', completed_at: '2026-09-23T10:00:13Z', final_response: 'Fixed the configuration parser and verified edge cases.', graders: [{ id: 'functional', component: 'functional', weight: .8, score: 1, passed: true, mandatory: true, summary: 'All hidden functional checks passed.', output: '4 passed in 0.12s', duration_ms: 120, infrastructure_error: false }, { id: 'regression', component: 'regression', weight: .1, score: 1, passed: true, mandatory: true, summary: 'Regression checks passed.', output: '2 passed', duration_ms: 120, infrastructure_error: false }, { id: 'constraints', component: 'constraints', weight: .1, score: 1, passed: true, mandatory: true, summary: 'Only allowed source files changed.', output: '', duration_ms: 10, infrastructure_error: false }], routes: [{ turn_index: 1, provider: 'test', model: 'test-router', response_model: 'test-fast' }, { turn_index: 2, provider: 'test', model: 'test-capable' }], artifacts: [{ id: 'artifact-stderr', kind: 'stderr', sha256: 'stderr-hash', byte_size: 0, truncated: false }] };
const leaderBase: Leader = { profile_id: 'mock-reference', label: 'Reference agent', mean_score: 1, median_score: 1, full_passes: 2, total_attempts: 2, pass_rate: 1, completion_rate: 1, median_agent_duration_ms: 12000, total_cost_usd: .02, median_cost_usd: .01, cost_coverage: 1, cost_provenance: 'reported', input_tokens: 3600, output_tokens: 800, tool_calls: 6, timeout_rate: 0, adapter_error_rate: 0, flake_rate: null, score_stddev: 0, score_min: 1, score_max: 1, quality_per_dollar: 100, quality_per_minute: 5, valid_attempts: 2, failures: { failed: 0, timed_out: 0, adapter_error: 0, infrastructure_error: 0 } };
export const finishedRun: Run = { id: 'run-one', status: 'completed', suite, profiles: profiles.slice(0, 2), mode: 'sequential', attempts_per_case: 1, timeout_seconds: 900, random_seed: 42, created_at: '2026-09-23T10:00:00Z', started_at: '2026-09-23T10:00:01Z', completed_at: '2026-09-23T10:01:00Z', total_attempts: 4, completed_attempts: 4, warnings: ['Cost is unavailable for Baseline agent.'], attempts: [attemptBase, { ...attemptBase, id: 'attempt-base-1', profile_id: 'mock-baseline', status: 'failed', score: .4, full_pass: false, cost_usd: null, cost_provenance: 'unavailable', primary_observed_model: null, routes: [], graders: [{ ...attemptBase.graders[0], score: .25, passed: false, summary: 'A boundary case failed.', output: '1 failed, 3 passed' }] }, { ...attemptBase, id: 'attempt-ref-2', case_id: 'RB-PY-002' }, { ...attemptBase, id: 'attempt-base-2', case_id: 'RB-PY-002', profile_id: 'mock-baseline', cost_usd: null, cost_provenance: 'unavailable', primary_observed_model: null, routes: [] }], leaderboard: [leaderBase, { ...leaderBase, profile_id: 'mock-baseline', label: 'Baseline agent', mean_score: .7, median_score: .7, full_passes: 1, pass_rate: .5, median_agent_duration_ms: 9000, total_cost_usd: null, median_cost_usd: null, cost_coverage: 0, cost_provenance: 'unavailable', quality_per_dollar: null, failures: { failed: 1, timed_out: 0, adapter_error: 0, infrastructure_error: 0 } }], winners: { best_quality: 'mock-reference', best_pass_rate: 'mock-reference', fastest_successful: 'mock-baseline', cheapest_successful: null, most_reliable: 'mock-reference' }, categories: [{ category: 'Bug repair', profile_id: 'mock-reference', score: 1 }, { category: 'Bug repair', profile_id: 'mock-baseline', score: .4 }, { category: 'Feature implementation', profile_id: 'mock-reference', score: 1 }, { category: 'Feature implementation', profile_id: 'mock-baseline', score: 1 }], pareto: { time: ['mock-reference', 'mock-baseline'], cost: ['mock-reference'] }, metric_availability: { cost: .5, route: .5 }, provisional: false };
export const runningRun: Run = { ...finishedRun, status: 'running', completed_at: null, completed_attempts: 1, provisional: true, attempts: finishedRun.attempts.map((a, i) => i === 0 ? a : { ...a, status: i === 1 ? 'running' : i === 2 ? 'grading' : 'queued', score: null, full_pass: null, agent_duration_ms: null, completed_at: null, started_at: new Date().toISOString() }) };
