import { expect, test } from '@playwright/test';

test('planning task is selectable alone and in core while smoke stays unchanged', async ({ page }) => {
  await page.goto('/');
  expect((await (await page.request.get('/api/v1/system')).json()).mock_enabled).toBe(true);
  const selector = page.getByLabel('Evaluation suite');
  await selector.selectOption('python-planning');
  await expect(page.locator('.suite-description')).toHaveText('1 task selected from RouteBench Python Core.');
  await expect(page.getByRole('button', { name: 'Start 2 evaluations' })).toBeEnabled();
  await page.locator('.suite-cases summary').click();
  await expect(page.locator('.case-list > div')).toHaveCount(1);
  await expect(page.getByText('Inventory reservations: plan, implement, verify', { exact: true })).toBeVisible();
  await selector.selectOption('python-core');
  await expect(page.locator('.case-list > div')).toHaveCount(9);
  await expect(page.getByText('RB-PY-009', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start 18 evaluations' })).toBeEnabled();
  await selector.selectOption('python-smoke');
  await expect(page.locator('.case-list > div')).toHaveCount(3);
  await expect(page.getByText('RB-PY-009', { exact: true })).toHaveCount(0);
});

test('actual local mock backend runs, grades, persists, and exports evidence', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.goto('/');
  const backend = await page.request.get('/api/v1/system');
  expect((await backend.json()).mock_enabled, 'Integration tests must never call real CLI profiles.').toBe(true);
  await expect(page.getByText('Test mode is active.', { exact: false })).toBeVisible();
  await expect(page.getByRole('checkbox', { name: 'Select Reference solution' })).toBeChecked();
  await page.screenshot({ path: '../.implementation/setup.png', fullPage: true });
  const created = page.waitForResponse(response => response.url().endsWith('/api/v1/runs') && response.request().method() === 'POST');
  await page.getByRole('button', { name: /^Start \d+ evaluations/ }).click();
  expect((await created).ok(), 'The real backend must accept the same-origin run request.').toBe(true);
  await expect(page.getByText('Evidence saved', { exact: true })).toBeVisible({ timeout: 90000 });
  await expect(page.getByRole('button', { name: /passed, score 100/ }).first()).toBeVisible();
  await page.getByRole('button', { name: /passed, score 100/ }).first().click();
  const drawer = page.getByRole('dialog');
  await expect(drawer.getByText('Why this score?')).toBeVisible();
  await expect(drawer.getByText('All mandatory checks passed', { exact: true })).toBeVisible();
  await drawer.getByRole('tab', { name: 'Diff', exact: true }).click();
  await expect(drawer.getByLabel('Repository patch')).toContainText('diff --git');
  await drawer.getByRole('tab', { name: 'Metadata' }).click();
  await expect(drawer.getByText('Fixture SHA-256', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close attempt inspector' }).click();
  await page.getByRole('tab', { name: 'Results overview' }).click();
  await expect(page.getByRole('heading', { name: 'Configuration leaderboard' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Cost', exact: true })).toBeDisabled();
  await page.screenshot({ path: '../.implementation/dashboard.png', fullPage: true });
  await page.locator('.export-menu summary').click();
  const exportUrl = await page.getByRole('link', { name: 'Complete run JSON' }).getAttribute('href');
  const exported = await page.request.get(exportUrl!); expect(exported.ok()).toBe(true);
  const body = await exported.json(); expect(JSON.stringify(body)).toContain('mock-reference');
  await page.locator('.export-menu summary').click();
  await page.getByRole('tab', { name: /Case matrix/ }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '../.implementation/mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'History', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Run history' })).toBeVisible();
  await expect(page.getByRole('link', { name: /Python.*smoke|Smoke/i }).first()).toBeVisible();
  expect(errors).toEqual([]);
});
