import { useCallback, useEffect, useState } from 'react';
import { API, active, color, date, duration, isReady, percent, request } from './api';
import type { Profile, Run, Suite, System } from './types';
import { RunView } from './RunView';
import { History } from './History';

export function ErrorNotice({ message, retry }: { message: string; retry?: () => void }) {
  return <div className="notice danger" role="alert"><span>{message}</span>{retry && <button className="text-button" onClick={retry}>Try again</button>}</div>;
}
export function Empty({ title, children }: { title: string; children?: React.ReactNode }) {
  return <div className="empty"><span className="empty-symbol" aria-hidden="true">⌁</span><h3>{title}</h3>{children}</div>;
}
export function Status({ status }: { status: string }) {
  const symbols: Record<string, string> = { passed: '✓', failed: '×', timed_out: '◷', adapter_error: '!', infrastructure_error: '⊘', cancelled: '−', completed: '✓', completed_with_errors: '!', running: '◉', grading: '⋯', preparing: '◌', queued: '○', ready: '✓', missing: '⊘', blocked: '!' };
  return <span className={`status status-${status}`}><span aria-hidden="true">{symbols[status] || '○'}</span>{status === 'ready' ? 'CLI ready' : status.replaceAll('_', ' ')}</span>;
}
export function ProfileName({ id, label }: { id: string; label: string }) { return <span className="profile-name"><i style={{ background: color(id) }} aria-hidden="true" />{label}</span>; }
function useLocation() {
  const [hash, setHash] = useState(location.hash.slice(1) || '/');
  useEffect(() => { const update = () => setHash(location.hash.slice(1) || '/'); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update); }, []);
  return hash;
}
export function App() {
  const path = useLocation();
  const [data, setData] = useState<{ profiles: Profile[]; suites: Suite[]; runs: Run[]; system: System }>();
  const [error, setError] = useState('');
  const load = useCallback(async () => {
    setError('');
    try {
      const [profiles, suites, runs, system] = await Promise.all([request<{ profiles: Profile[] }>('/profiles'), request<{ suites: Suite[] }>('/suites'), request<{ runs: Run[] }>('/runs'), request<System>('/system')]);
      setData({ profiles: profiles.profiles, suites: suites.suites, runs: runs.runs, system });
    } catch (err) { setError((err as Error).message); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (data && (path === '/' || path === '/history')) void request<{ runs: Run[] }>('/runs').then(r => setData(d => d ? { ...d, runs: r.runs } : d)).catch(err => setError(err.message)); }, [path]);
  const runId = path.startsWith('/runs/') ? decodeURIComponent(path.split('/')[2]) : null;
  return <><a className="skip" href="#main" onClick={e => { e.preventDefault(); document.getElementById("main")?.focus(); }}>Skip to content</a><header className="topbar"><a href="#/" className="brand" aria-label="RouteBench home"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 7v18m0-9h10q8 0 8-9M7 16h10q8 0 8 9"/><circle cx="7" cy="7" r="3"/><circle cx="25" cy="7" r="3"/><circle cx="25" cy="25" r="3"/></svg><span>Route<span className="brand-light">Bench</span></span></a><nav aria-label="Main navigation"><a href="#/" className={path === '/' ? 'selected' : ''}>New run</a><a href="#/history" className={path === '/history' ? 'selected' : ''}>History</a><a href="#/settings" className={path === '/settings' ? 'selected' : ''}>Settings</a></nav><div className="header-end"><span className="local"><i />Local workspace</span><a href={`${API}/documentation`} target="_blank" rel="noreferrer" className="documentation">Documentation ↗</a></div></header>
    <main id="main" className="main" tabIndex={-1}>
      {error && <ErrorNotice message={error} retry={load} />}
      {!data ? !error && <div className="loading" role="status">Connecting to your local lab…</div> : runId ? <RunView key={runId} id={runId} /> : path === '/history' ? <History runs={data.runs} reload={load} /> : path === '/settings' ? <Settings profiles={data.profiles} system={data.system} onPreflight={async () => { const r = await request<{ profiles: Profile[] }>('/profiles/preflight', { method: 'POST' }); setData(d => d ? { ...d, profiles: r.profiles } : d); }} /> : <NewRun {...data} onProfiles={profiles => setData(d => d ? { ...d, profiles } : d)} />}
    </main><footer className="footer"><span>RouteBench <span className="muted">/</span> Configuration comparisons, backed by evidence.</span><span className="mono">{data?.system.version ? `v${data.system.version}` : 'Local evaluation lab'}</span></footer>
  </>;
}

export function NewRun({ profiles, suites, runs, system, onProfiles }: { profiles: Profile[]; suites: Suite[]; runs: Run[]; system: System; onProfiles: (p: Profile[]) => void }) {
  const [suiteId, setSuiteId] = useState(suites.find(s => s.id.includes('smoke'))?.id || suites[0]?.id || '');
  const [selected, setSelected] = useState(profiles.filter(p => isReady(p) && p.preflight?.model_access !== 'last_execution_failed').map(p => p.id));
  const [attempts, setAttempts] = useState(system.defaults.attempts_per_case === 3 ? 3 : 1);
  const [mode, setMode] = useState(system.defaults.mode || 'sequential');
  const [timeout, setTimeout] = useState(system.defaults.timeout_seconds || 900);
  const [seed, setSeed] = useState(42);
  const [keep, setKeep] = useState(system.storage.keep_workspaces);
  const [busy, setBusy] = useState(false);
  const [checking, setChecking] = useState(false);
  const [error, setError] = useState('');
  const suite = suites.find(s => s.id === suiteId);
  const readySelected = selected.filter(id => profiles.some(p => p.id === id && isReady(p)));
  const total = (suite?.cases.length || 0) * readySelected.length * attempts;
  const valid = total > 0 && Number.isInteger(timeout) && timeout >= 1 && timeout <= 7200 && Number.isInteger(seed) && seed >= 0;
  const preflight = async () => { setChecking(true); setError(''); try { const r = await request<{ profiles: Profile[] }>('/profiles/preflight', { method: 'POST' }); onProfiles(r.profiles); setSelected(r.profiles.filter(p => isReady(p) && p.preflight?.model_access !== 'last_execution_failed').map(p => p.id)); } catch (err) { setError((err as Error).message); } finally { setChecking(false); } };
  const start = async () => {
    if (!valid || busy) return;
    setBusy(true); setError('');
    try { const run = await request<{ id: string }>('/runs', { method: 'POST', body: JSON.stringify({ suite_id: suiteId, profile_ids: readySelected, attempts_per_case: attempts, mode, timeout_seconds: timeout, random_seed: seed, keep_workspaces: keep }) }); location.hash = `/runs/${encodeURIComponent(run.id)}`; }
    catch (err) { setError((err as Error).message); setBusy(false); }
  };
  return <>
    <div className="page-heading setup-heading"><div><span className="kicker">Your local evaluation lab</span><h1>Compare coding agents<br/>with evidence.</h1><p>One suite. Identical starting points. Every result open to inspection.</p></div><div className="method-note"><span className="method-icon" aria-hidden="true">≋</span><div><strong>Measure the whole configuration</strong><p>Model + harness + routing.<br/>Correctness first. Time and cost in context.</p></div></div></div>
    {system.mock_enabled && <div className="notice info">Test mode is active. Demo profiles produce synthetic execution results for validating RouteBench.</div>}
    {error && <ErrorNotice message={error} />}
    <div className="setup-layout"><div className="setup-main"><section className="panel suite-panel"><div className="section-heading"><div><h2>Evaluation suite</h2><p>The same tasks and graders for every configuration.</p></div><span className="step">1</span></div><label className="sr-only" htmlFor="suite">Evaluation suite</label><select id="suite" value={suiteId} onChange={e => setSuiteId(e.target.value)}>{suites.map(s => <option key={s.id} value={s.id}>{s.name} / v{s.version}</option>)}</select>{suite ? <><p className="suite-description">{suite.description}</p><div className="suite-details"><span><strong>{suite.cases.length}</strong> deterministic cases</span><span><strong>{new Set(suite.cases.map(c => c.category)).size}</strong> categories</span><span>Hidden tests + constraints</span></div><details className="suite-cases"><summary>Inspect the case set <span>{suite.cases.length} cases</span></summary><div className="case-list">{suite.cases.map(c => <div key={c.id}><span className="mono muted">{c.id}</span><strong>{c.title}</strong><span className="tag">{c.category}</span></div>)}</div></details></> : <p className="muted">No valid suites found. Check the local suite configuration.</p>}</section>
      <section className="panel"><div className="section-heading"><div><h2>Agent configurations <span className="count">{readySelected.length} selected</span></h2><p>Select the CLI and model combinations to compare.</p></div><span className="step">2</span></div><div className="profiles">{profiles.map(profile => {
        const ready = isReady(profile); const checked = readySelected.includes(profile.id); const caps = profile.preflight?.capabilities;
        return <label key={profile.id} className={`profile-card ${checked ? 'is-selected' : ''} ${!ready ? 'unavailable' : ''}`} style={{ '--profile': color(profile.id) } as React.CSSProperties}><div className="profile-top"><span className="adapter-icon">{profile.adapter === 'pi' ? 'π' : profile.adapter === 'claude' ? '✳' : '⌘'}</span><input type="checkbox" aria-label={`Select ${profile.label}`} disabled={!ready || checking || busy} checked={checked} onChange={() => setSelected(previous => checked ? previous.filter(id => id !== profile.id) : [...previous, profile.id])}/></div><strong>{profile.label}</strong><span className="profile-model mono">{profile.adapter} / {profile.model}</span><div className="profile-state"><Status status={!profile.enabled ? 'disabled' : profile.preflight?.status || 'not_checked'} /><span className="mono version">{profile.preflight?.version || 'Version unchecked'}</span></div><div className="profile-capabilities"><span>{caps?.reported_cost || profile.pricing ? '✓ Cost available' : '— Cost unavailable'}</span><span>{caps?.route ? '✓ Route events' : '— Route unavailable'}</span></div><p className="field-note">{profile.adapter === 'mock' ? 'Local simulation · no model calls' : profile.preflight?.model_access === 'verified_in_previous_run' ? 'Model access: verified in a previous run' : profile.preflight?.model_access === 'last_execution_failed' ? 'Model access: last execution failed' : 'Model access: not verified by a completed run'}</p>{profile.preflight?.model_access === 'last_execution_failed' && <p className="profile-warning">Last execution failed. Select explicitly to retry.<br/>{profile.preflight.warnings.find(w => w.startsWith('Last execution:'))}</p>}{!ready && <p className="profile-warning">{profile.preflight?.warnings?.[0] || (!profile.enabled ? 'Disabled in local configuration.' : 'Run preflight to check CLI readiness.')}</p>}</label>;
      })}</div>{profiles.length === 0 && <Empty title="No profiles configured"><p>Add a CLI profile to the local configuration, then refresh.</p></Empty>}<div className="preflight-row"><span><span className="status-dot" />{profiles.filter(isReady).length} of {profiles.length} CLIs ready · model access checked by execution</span><button onClick={preflight} disabled={checking || busy} className="button small">{checking ? 'Checking CLIs…' : 'Run preflight'}</button></div></section>
    </div><aside className="setup-aside"><section className="panel run-settings"><div className="section-heading"><div><h2>Run controls</h2><p>Keep the comparison repeatable.</p></div><span className="step">3</span></div><label>Execution mode<select value={mode} onChange={e => setMode(e.target.value)}><option value="sequential">Sequential · recommended</option><option value="parallel">Parallel</option></select></label><p className="field-note">{mode === 'sequential' ? 'One agent at a time reduces local resource contention.' : 'Concurrent agents share host resources. Latency is less comparable.'}</p><div className="field-pair"><label>Attempts per case<select value={attempts} onChange={e => setAttempts(+e.target.value)}><option value={1}>1 attempt</option><option value={3}>3 attempts</option></select></label><label>Timeout (seconds)<input type="number" min={1} max={7200} value={timeout} onChange={e => setTimeout(+e.target.value)}/></label></div><details className="advanced"><summary>Reproducibility & storage</summary><label>Random seed<input type="number" min={0} value={seed} onChange={e => setSeed(+e.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={keep} onChange={e => setKeep(e.target.checked)}/>Keep attempt workspaces</label></details><div className="run-equation"><span>{suite?.cases.length || 0} cases × {readySelected.length} profiles × {attempts} attempt{attempts === 1 ? '' : 's'}</span><div><strong>{total}</strong><span>evaluations</span></div></div><button className="button primary start" disabled={!valid || busy || checking} onClick={start}>{busy ? 'Preparing run…' : `Start ${total} evaluations`}<span aria-hidden="true">▶</span></button>{!readySelected.length && <p className="field-note">Choose at least one ready configuration to begin.</p>}<p className="execution-note">Agent time is measured separately from preparation and grading.</p></section><div className="setup-advisory"><span aria-hidden="true">ⓘ</span><p>Workspace copies isolate task state; CLI permission policies determine host access. Use trusted fixtures.</p></div>{profiles.filter(p => readySelected.includes(p.id)).flatMap(p => p.preflight?.warnings?.map((w, i) => <div className="notice warning compact" key={`${p.id}-${i}`}>{p.label}: {w}</div>) || [])}{readySelected.some(id => { const p = profiles.find(p => p.id === id)!; return !p.pricing && !p.preflight?.capabilities?.reported_cost; }) && <div className="notice warning compact">Some selected profiles have no trustworthy price. Their cost metrics will remain unavailable.</div>}</aside></div>
    <section className="recent"><div className="section-heading"><div><h2>Recent runs</h2><p>Your evidence stays on this machine.</p></div><a href="#/history" className="text-link">View history ↗</a></div>{runs.length ? <div className="recent-runs">{runs.slice(0, 3).map(run => <a className="recent-run" href={`#/runs/${encodeURIComponent(run.id)}`} key={run.id}><div><Status status={run.status}/><span className="muted">{date(run.created_at)}</span></div><strong>{run.suite.name}</strong><span>{run.profiles.length} profiles · {run.completed_attempts}/{run.total_attempts} evaluations</span><span className="mono muted">{run.id}</span></a>)}</div> : <Empty title="Your first comparison starts here"><p>Choose the smoke suite to check your local setup before a full evaluation.</p></Empty>}</section>
  </>;
}

function Settings({ profiles, system, onPreflight }: { profiles: Profile[]; system: System; onPreflight: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <><div className="page-heading"><div><span className="kicker">Local configuration</span><h1>Settings</h1><p>Read-only runtime status. Edit your local configuration to change these defaults.</p></div><button className="button" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await onPreflight(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }}>{busy ? 'Checking…' : 'Run CLI preflight'}</button></div>{error && <ErrorNotice message={error}/>}<div className="settings-grid"><section className="panel"><h2>Evaluation defaults</h2><dl className="metadata"><div><dt>Execution</dt><dd>{system.defaults.mode}</dd></div><div><dt>Attempt timeout</dt><dd>{duration(system.defaults.timeout_seconds * 1000)}</dd></div><div><dt>Attempts per case</dt><dd>{system.defaults.attempts_per_case}</dd></div><div><dt>Artifact retention</dt><dd>{system.storage.retention_days} days</dd></div><div><dt>Keep workspaces</dt><dd>{system.storage.keep_workspaces ? 'Yes' : 'No'}</dd></div><div><dt>Storage</dt><dd>Local workspace & SQLite</dd></div><div><dt>Network exposure</dt><dd>{system.local_only ? 'Loopback only' : 'See server configuration'}</dd></div></dl><p className="field-note">Paths and authentication values are omitted from this screen. See the local configuration for storage locations.</p></section><section className="panel"><h2>Configuration health</h2><p className="muted">{profiles.filter(isReady).length} of {profiles.length} CLIs ready; model access checked by execution</p><div className="health-list">{profiles.map(p => <div key={p.id}><div><ProfileName id={p.id} label={p.label}/><Status status={p.preflight?.status || 'not_checked'}/></div><span className="mono muted">{p.adapter} / {p.model}</span><small>Version: {p.preflight?.version || 'Not checked'} · Authentication: {p.preflight?.authentication?.replaceAll('_', ' ') || 'Not checked'}</small><small>Pricing: {p.pricing ? 'Configured locally' : p.preflight?.capabilities?.reported_cost ? 'Reported by CLI' : 'Unavailable'}</small>{p.preflight?.warnings?.map((w, i) => <p className="warning-text" key={i}>{w}</p>)}</div>)}</div></section></div>{system.warnings?.map((w, i) => <div key={i} className="notice warning">{w}</div>)}</>;
}
