import { useEffect, useRef, useState } from 'react';
import { active, date, duration, number, percent, request, score } from './api';
import type { AttemptDetail, Run } from './types';
import { CostAmount, CostBreakdown } from './Cost';
import { Empty, ErrorNotice, ProfileName, Status } from './App';

type SafeEvent = { type?: string; timestamp?: string; created_at?: string; tool?: string | { name?: string }; text?: string; summary?: string; route?: { model?: string; provider?: string }; turn_index?: number; [key: string]: unknown };
const tabs = ['Evidence', 'Diff', 'Timeline', 'Output', 'Metadata'];
export function Inspector({ id, refreshKey, lastEvent, onClose, onRerun }: { id: string; refreshKey: Run; lastEvent?: string; onClose: () => void; onRerun: (id: string) => void }) {
  const [attempt, setAttempt] = useState<AttemptDetail>(); const [tab, setTab] = useState('Evidence');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [diff, setDiff] = useState<string>(); const [events, setEvents] = useState<{ events: SafeEvent[]; total: number }>(); const [stderr, setStderr] = useState<string>();
  const closeButton = useRef<HTMLButtonElement>(null);
  const returnFocus = useRef<HTMLElement | null>(document.activeElement as HTMLElement);
  useEffect(() => { closeButton.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', escape); return () => { document.removeEventListener('keydown', escape); returnFocus.current?.focus(); }; }, []);
  useEffect(() => { setTab('Evidence'); setDiff(undefined); setEvents(undefined); setStderr(undefined); setAttempt(undefined); }, [id]);
  useEffect(() => { let valid = true; request<AttemptDetail>(`/attempts/${encodeURIComponent(id)}`).then(a => { if (valid) { setAttempt(a); setError(''); } }).catch(err => { if (valid) setError(err.message); }); return () => { valid = false; }; }, [id, refreshKey]);
  useEffect(() => {
    let valid = true;
    if (tab === 'Diff') request<string>(`/attempts/${encodeURIComponent(id)}/diff`).then(d => { if (valid) setDiff(d); }).catch(err => { if (valid) setError(err.message); });
    if (tab === 'Timeline') request<{ events: SafeEvent[]; total: number }>(`/attempts/${encodeURIComponent(id)}/events?offset=0&limit=100`).then(d => { if (valid) setEvents(d); }).catch(err => { if (valid) setError(err.message); });
    const stderrArtifact = attempt?.artifacts.find(a => a.kind === 'stderr');
    if (tab === 'Output' && stderrArtifact) request<string>(`/artifacts/${encodeURIComponent(stderrArtifact.id)}`).then(d => { if (valid) setStderr(d); }).catch(err => { if (valid) setError(err.message); });
    return () => { valid = false; };
  }, [id, tab, attempt?.status, attempt?.artifacts.length]);
  const rerun = async () => { setBusy(true); setError(''); try { const result = await request<{ id: string }>(`/attempts/${encodeURIComponent(id)}/rerun`, { method: 'POST' }); onRerun(result.id); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  const loadMore = async () => { if (!events) return; setBusy(true); try { const more = await request<{ events: SafeEvent[]; total: number }>(`/attempts/${encodeURIComponent(id)}/events?offset=${events.events.length}&limit=100`); setEvents({ events: [...events.events, ...more.events], total: more.total }); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  return <aside className="inspector" role="dialog" aria-modal="false" aria-labelledby="inspector-title"><header className="inspector-heading"><div><span className="mono muted">Attempt inspector / {attempt?.case_id || id}</span><h2 id="inspector-title">{attempt?.case.title || 'Opening evidence…'}</h2>{attempt && <ProfileName id={attempt.profile_id} label={attempt.profile.label}/>}</div><button className="close-button" ref={closeButton} onClick={onClose} aria-label="Close attempt inspector">×</button></header>{error && <ErrorNotice message={error}/>}{attempt ? <><div className="inspector-summary"><Status status={attempt.status}/><div><strong className="mono">{score(attempt.score)}</strong><span>Score / 100</span></div><div><strong className="mono">{duration(attempt.agent_duration_ms)}</strong><span>Agent time</span></div><div><CostAmount value={attempt.cost_usd} provenance={attempt.cost_provenance} sources={attempt.cost_estimate ? [attempt.cost_estimate.pricing] : []}/></div><div><strong className="mono">{number(attempt.input_tokens)} / {number(attempt.output_tokens)}</strong><span>Tokens in / out</span></div></div>{active(attempt.status) && <div className="live-evidence"><span className="connection is-live"><i/>{attempt.status}</span><p>{lastEvent || 'Waiting for the next safe normalized event. Hidden reasoning is not streamed.'}</p>{attempt.primary_observed_model && <span className="route-badge">⌁ {attempt.primary_observed_model}</span>}</div>}{attempt.error_message && <div className={`notice ${attempt.status === 'infrastructure_error' ? 'info' : 'danger'}`}><strong>{attempt.error_code || 'Execution issue'}</strong><span>{attempt.error_message}</span></div>}<div className="inspector-tabs" role="tablist" aria-label="Attempt evidence tabs" onKeyDown={e => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) return; e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? tabs.length - 1 : (tabs.indexOf(tab) + (e.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; setTab(tabs[next]); document.getElementById(`inspector-tab-${tabs[next]}`)?.focus(); }}>{tabs.map(t => <button key={t} id={`inspector-tab-${t}`} role="tab" aria-selected={tab === t} tabIndex={tab === t ? 0 : -1} aria-controls="inspector-content" onClick={() => { setTab(t); setError(''); }}>{t}</button>)}</div><div className="inspector-content" id="inspector-content" role="tabpanel" aria-labelledby={`inspector-tab-${tab}`}>
      {tab === 'Evidence' && <>{attempt.cost_estimate && <CostBreakdown estimate={attempt.cost_estimate}/>}{attempt.status === 'infrastructure_error' && <div className="notice info">This attempt is unscored because the evaluation infrastructure failed. Repair the cause and rerun; it is not an agent correctness failure.</div>}<div className="section-heading"><div><h3>Why this score?</h3><p>Every component is recorded independently.</p></div>{!active(attempt.status) && <span className={`tag ${attempt.full_pass ? 'success-text' : ''}`}>{attempt.full_pass ? 'All mandatory checks passed' : attempt.score == null ? 'Unscored' : 'Not a full pass'}</span>}</div>{attempt.graders?.length ? <div className="graders">{attempt.graders.map(g => <details className={`grader ${g.infrastructure_error ? 'grader-infra' : g.passed ? 'grader-pass' : 'grader-fail'}`} key={g.id}><summary><span className="grader-symbol">{g.infrastructure_error ? '⊘' : g.passed ? '✓' : '×'}</span><span className="grader-name"><strong>{g.id}</strong><span>{g.component} · {percent(g.weight)} weight {g.mandatory && <span className="mandatory">Mandatory</span>}</span></span><span className="mono">{g.infrastructure_error ? 'Unscored' : `${score(g.score)}/100`}</span></summary><div className="grader-body"><p>{g.summary || (g.passed ? 'Checks passed.' : 'Checks did not pass.')}</p><span className="field-note">{g.infrastructure_error ? 'Infrastructure failure' : g.passed ? 'Passed' : 'Failed'} · {duration(g.duration_ms)}</span><pre className="code-block">{g.output || 'No additional grader output.'}</pre></div></details>)}</div> : <Empty title={active(attempt.status) ? 'Grading has not completed' : 'No grader results recorded'}><p>{active(attempt.status) ? 'The score breakdown appears after execution and grading.' : 'Check the execution status and metadata for the reason.'}</p></Empty>}<details className="prompt-details"><summary>Canonical task prompt</summary><pre className="prose-output">{attempt.prompt}</pre></details></>}
      {tab === 'Diff' && <><div className="diff-stats"><span>{attempt.files_changed || 0} files changed</span><span className="success-text">+{attempt.lines_added || 0}</span><span className="failure-text">−{attempt.lines_removed || 0}</span></div>{diff === undefined ? <p role="status">Loading patch…</p> : diff ? <pre className="diff code-block" aria-label="Repository patch">{diff.split('\n').map((line, i) => <span key={i} className={line.startsWith('+++') || line.startsWith('---') || line.startsWith('diff ') ? 'diff-file' : line.startsWith('+') ? 'diff-add' : line.startsWith('-') ? 'diff-remove' : line.startsWith('@@') ? 'diff-hunk' : ''}>{line || ' '}<br/></span>)}</pre> : <Empty title="No repository changes"><p>No patch was recorded for this attempt.</p></Empty>}</>}
      {tab === 'Timeline' && <><h3>Normalized execution events</h3><p className="muted">Messages, tools, retries, and route changes. Hidden reasoning is omitted.</p>{events === undefined ? <p role="status">Loading timeline…</p> : <><ol className="event-timeline">{events.events.filter(e => !/thinking|reasoning/i.test(e.type || '')).map((e, i) => <li key={i}><span className="event-marker"/><div className="event-header"><strong>{(e.type || 'event').replaceAll('_', ' ')}</strong><span className="mono muted">{e.turn_index != null ? `Turn ${e.turn_index}` : ''} {e.timestamp || e.created_at ? date(e.timestamp || e.created_at) : ''}</span></div>{e.tool && <span className="tag mono">{typeof e.tool === 'string' ? e.tool : e.tool.name || 'Tool event'}</span>}{e.route && <span className="route-badge">⌁ {e.route.provider} / {e.route.model}</span>}{(e.summary || e.text) && <pre className="event-text">{String(e.summary || e.text)}</pre>}</li>)}</ol>{!events.events.length && <Empty title="No normalized events recorded"/>}{events.events.length < events.total && <button className="button" disabled={busy} onClick={loadMore}>{busy ? 'Loading…' : `Load more events (${events.events.length}/${events.total})`}</button>}</>}</>}
      {tab === 'Output' && <><h3>Final agent response</h3><pre className="prose-output">{attempt.final_response || 'No final response recorded.'}</pre><h3>Sanitized standard error</h3><pre className="code-block">{stderr ?? (attempt.artifacts.some(a => a.kind === 'stderr') ? 'Loading sanitized stderr…' : 'No standard error artifact recorded.')}</pre>{attempt.artifacts.filter(a => a.truncated).map(a => <div key={a.id} className="notice warning compact">{a.kind} was truncated at the artifact size limit.</div>)}</>}
      {tab === 'Metadata' && <><h3>Reproducibility record</h3><dl className="metadata">{Object.entries({ 'Attempt ID': attempt.id, 'Run ID': attempt.run_id, 'Case ID': attempt.case_id, 'Attempt index': attempt.attempt_index, 'Execution order': attempt.execution_order, 'Configured model': attempt.configured_model, 'Observed model': attempt.primary_observed_model || 'Unavailable', 'CLI version': attempt.profile.preflight?.version || 'Unavailable', 'Fixture SHA-256': attempt.fixture_hash, 'Prompt SHA-256': attempt.prompt_hash, 'Created': date(attempt.created_at), 'Agent started': date(attempt.started_at), 'Completed': date(attempt.completed_at), 'Preparation': duration(attempt.preparation_duration_ms), 'Agent': duration(attempt.agent_duration_ms), 'Grading': duration(attempt.grading_duration_ms), 'Exit code': attempt.exit_code ?? '—', 'Cached input tokens': number(attempt.cached_input_tokens), 'Reasoning tokens': number(attempt.reasoning_tokens), 'Tool calls': number(attempt.tool_calls), 'Turns': number(attempt.turns), 'Retries': number(attempt.retries), 'Supersedes attempt': attempt.supersedes_attempt_id || 'None' }).map(([key, value]) => <div key={key}><dt>{key}</dt><dd className="mono">{value}</dd></div>)}</dl><h3>Redacted command preview</h3><pre className="code-block">{attempt.command_preview?.join('\n') || 'No command preview recorded.'}</pre><h3>Observed routes</h3>{attempt.routes.length ? <ol className="metadata-routes">{attempt.routes.map((r, i) => <li key={i}>Turn {r.turn_index}: {r.provider} / <strong>{r.model}</strong>{r.response_model && r.response_model !== r.model && ` (response: ${r.response_model})`}</li>)}</ol> : <p className="muted">Route metadata unavailable.</p>}<h3>Artifact fingerprints</h3><dl className="metadata">{attempt.artifacts.map(a => <div key={a.id}><dt>{a.kind} / {number(a.byte_size)} bytes</dt><dd className="mono">{a.sha256}</dd></div>)}</dl></>}
    </div><footer className="inspector-footer"><span className="mono muted">{id}</span>{!refreshKey.security_blocked && ['infrastructure_error', 'cancelled'].includes(attempt.status) && attempt.error_code !== 'security_blocked' && <button className="button small" disabled={busy || active(refreshKey.status)} title={active(refreshKey.status) ? 'Wait for the current run to finish before rerunning.' : 'Preserves the original attempt and creates a new one.'} onClick={rerun}>{busy ? 'Scheduling…' : 'Rerun attempt'}</button>}</footer></> : !error && <div className="loading" role="status">Loading recorded evidence…</div>}</aside>;
}
